WOK-AT/WOKAT-SERVER

.github/workflows/docker.yml
Dockerfile

- [Deploy] 도커 이용해 CI/CD 구축하기
- Dockerfile 생성
- .github/workflows/docker.yml 통해 CI/CD 진행할 수 있도록 구성 
- CI : Main 브랜치로 PR 생성 /  Main 브랜치로 PR Merge / Main 브랜치로 Push
- CD : Main 브랜치로 PR Merge / Main 브랜치로 Push

[Deploy] Docker 이용한 CI/CD 구축

---

.github/workflows/docker.yml

- 첫 배포 후 주석 삭제
- 도커 테스트 완료
- PR 머지, Main 푸쉬시에만 CD 진행하도록 수정 
- docker rmi 추가 
- docker rmi 주석 해제
- if PR 머지, Main 푸쉬시 주석 해제

[Refactor] 주석 삭제

---

.gitignore
build.gradle
src/main/java/com/sopt/wokat/WokatApplication.java
src/main/resources/log4j2-dev.xml
src/main/resources/log4j2-prod.xml
src/test/java/com/sopt/wokat/log/logFileTest.java

Log4j2 로그 설정
1. 로그파일 저장할 수 있도록 로직 구성
log4j2-dev.xml → 개발환경 로그
log4j2-prod.xml → 배포환경 로그
- 배포 : 6시간 / 개발 : 하루 단위 압축 로그파일 생성  후 원본파일 삭제 
2.  Docker에 Volume 옵션 이용
: 서버의 `~/logs` 경로에 로그 저장되게 구성 
3. 사용방법
`private final Logger LOGGER = LogManager.getLogger(this.getClass());` 으로 LOGGER 인스턴스 생성
-> `LOGGER.info`, `LOGGER.error` 와 같은 방식으로 사용 
- build.gradle에 Springboot의 기본 로깅 모듈 **Logback** 제외해 **Log4j2**와 충돌 방지

[Settings] Log4j2 로그 설정 

---

build.gradle
src/main/java/com/sopt/wokat/global/config/SwaggerConfig.java

- Swagger 설정 
> Springdoc 이용해 swagger 설정 완료
[로컬환경] http://localhost:8080/swagger-ui.html
[배포환경] http://3.129.172.207:8080/swagger-ui.html

[Setting] Swagger 설정

---

src/main/java/com/sopt/wokat/domain/user/dto/UserDTO.java
src/main/java/com/sopt/wokat/domain/user/entity/User.java
src/main/java/com/sopt/wokat/domain/user/exception/JwtInvalidException.java
src/main/java/com/sopt/wokat/domain/user/repository/UserRepository.java
src/main/java/com/sopt/wokat/domain/user/service/UserService.java

- 예시 User 디렉토리 작성 
- 예시 User 디렉토리 작성 
- controller, dto, entity, exception, repository, service 디렉토리 추가

[Add] 예시 디렉토리 생성

---

src/main/java/com/sopt/wokat/domain/member/controller/MemberController.java
src/main/java/com/sopt/wokat/domain/member/controller/OauthController.java
src/main/java/com/sopt/wokat/domain/member/dto/MemberResponse.java
src/main/java/com/sopt/wokat/domain/place/entity/Space.java
src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
src/main/java/com/sopt/wokat/global/config/SwaggerConfig.java

- 공간 엔티티 작성
- Space.java, SpaceInfo.java 생성
- 0(무료공간)/1(무료회의룸)/2(카페) enum 클래스로 Space 나눔

[Feature] 공간 엔티티 작성

---

src/main/java/com/sopt/wokat/domain/member/service/OauthService.java
src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/exception/PlaceNotFoundException.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
src/main/java/com/sopt/wokat/global/config/security/WebSecurityConfig.java
src/main/java/com/sopt/wokat/global/config/security/filter/JwtAuthenticationFilter.java
src/main/java/com/sopt/wokat/global/error/ErrorCode.java
src/main/java/com/sopt/wokat/global/result/ResultCode.java
src/test/java/com/sopt/wokat/DB/RedisTest.java
src/test/java/com/sopt/wokat/aws/s3/ImageUploadTest.java

특정 장소 조회 API 추가
- [POST] /place/:placeId
- 특정 장소 선택 시, 장소의 정보를 반환하는 로직 추가

[Feature] 특정 장소 조회 

---

src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceRequest.java
src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/test/java/com/sopt/wokat/DB/PlaceTest.java

- SpaceInfo 컬럼 타입 변경
- boolean -> string 변경

[Refactor] SpaceInfo boolean -> string

---

src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java

- 특정 공간 조회 시, 무료공간이자 무료회의룸인 곳 때문에, placeList를 받지 않으면 어떤 카테고리로 리턴해야할지 모름 
- /:placeList 추가 
- hashtag 리턴 데이터 변경 
- /place/:placeId -> /place/:placeList/:placeId
- hashtag가 없는 경우, [""] 반환 대신 [] 반환으로 변경

[Fix] uri 변경 및 리턴 값 변경

---

src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceRequest.java
src/main/java/com/sopt/wokat/domain/place/entity/Space.java
src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
src/main/java/com/sopt/wokat/global/config/security/WebSecurityConfig.java
src/main/java/com/sopt/wokat/global/result/ResultCode.java
src/main/resources/application.yml

- Issue 번호 #25 
- 데이터 수정됨에 따라 관련 로직 수정
- URI 변경 /place/:placeList.]/:placeId -> /place/:placeId
- 공간 카테고리 수정 
- 무료공간+무료회의룸인 ZONE_AND_ROOM 삭제

[Feature] 공간 상세 검색 API 수정 

---

src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
src/main/java/com/sopt/wokat/domain/place/dto/FilteringPlaceRequest.java
src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceRequest.java
src/main/java/com/sopt/wokat/domain/place/entity/Space.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java
src/main/java/com/sopt/wokat/global/config/security/WebSecurityConfig.java
src/main/java/com/sopt/wokat/global/result/ResultCode.java

- [GET] /place/filter/:placeList?area=&filter=&date=&headCount=&page=
- @ehdwoKIM PR 날린거 1차 정리 후 해야할 거 정리

[Feature] 공간 필터링 1차 정리

---

src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java

- [GET] /place/filter/:placeList
- uri 디코딩 기능 추가
- /place/filter/2?station=%EC%9E%A0%EC%9B%90&page=0&filter=1 형식의 요청이 들어오면 station을 decode하는 코드 추가

[Feature] url의 station을 utf-8로 디코딩하는 코드 추가

---

src/main/java/com/sopt/wokat/domain/place/dto/FilteringPlaceResponse.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java

- [GET] /place/filtering/:placeList
- response dto 변경
- 필터링 데이터 response에 공간 id 추가

[Feature] 필터링 시 공간 id response 추가

---

src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/test/java/com/sopt/wokat/DB/PlaceTest.java

- space_headcount -> space_headCount

[HotFix] space 수용인원 추가

---

src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java

[Hotfix] wifi 추가

---

src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java

- Issue 번호 #37 
- 오픈시간 순서대로 정렬 로직 변경  
- 오픈시간 빠른 순서대로 정렬
- 오픈시간 같은 경우, 마감시간 빠른 순서대로 정렬

[Fix] 오픈시간 빠른 순서대로 정렬

---

src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/dto/PostPlaceRequest.java
src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java

- 공간소개를 배열이 아닌 하나의 String으로 묶음 
- SpaceInfo 엔티티의 introduction 타입 변경 
-  `List<String>`   =>   `String`

[Fix] 공간소개 List<String> -> String 변경

---

src/main/java/com/sopt/wokat/domain/place/entity/SpaceInfo.java

- SpaceInfo.java @Field값 booking_url -> homepage_url로 변경

[Fix] bookingURL null값으로 넘어오는 문제

---

src/main/java/com/sopt/wokat/domain/place/controller/PlaceController.java
src/main/java/com/sopt/wokat/domain/place/dto/FilteringPlaceResponse.java
src/main/java/com/sopt/wokat/domain/place/dto/OnePlaceInfoResponse.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java

- Issue 번호 #45 
- [GET] /place/:placeId?station, /place/filter/:placeList?page=&filter=&station=
- 도보거리 데이터 여러 개인 경우, 하나만 반환하도록 수정 
- 검색한 역에 해당하는 도보거리 존재 -> 해당 도보거리 하나 반환
- 존재 x -> 최소 도보거리 하나 반환 
- 특정 장소 조회 API -> station 쿼리파라미터 추가

[QA] 도보거리 데이터 여러 개인 경우 하나만 반환

---

src/main/java/com/sopt/wokat/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/com/sopt/wokat/domain/place/service/PlaceService.java

- [GE] /place/filter/:placeList?page=&filter=&station=
- 이미지가 없는 장소의 경우, 대표 이미지로 null을 반환함

[Hotfix] 이미지 없는 장소 null 반환
